
if [ $# -eq 0 ];
then
    echo "usage: $0 version [release]"
    echo
    echo "Example:"
    echo "  $0   1.2   1.2-rc2"
    exit 1
fi

VERSION="$1"
if [ $# -eq 2 ];
then
    RELEASE="$2"
else
    RELEASE="$1"
fi

BEFORE=`md5sum pypsi/release.py`

cat > pypsi/release.py <<EOF
#
# This file is auto generated and will be overwritten, do not edit this file.
#
__version__ = "$VERSION"
__release__ = "$RELEASE"
EOF

AFTER=`md5sum pypsi/release.py`

echo "==================== Tagging Git ========================="

if [ "$BEFORE" = "$AFTER" ];
then
    git add pypsi/release.py
    git commit -m "updated to v$RELEASE"
fi

git tag --sign --message "tagged v$RELEASE" "v$RELEASE"
git push origin --tags
echo "=========================================================="
echo

set -e

echo "==================== Building Release ===================="
python setup.py sdist bdist_wheel upload --sign
echo "=========================================================="
echo

echo "==================== Building Docs ======================="
make -C docs/ clean
make -C docs/ html
pushd docs/build/html
zip -r "../../../pypsi_docs-$RELEASE.zip" *
popd
echo "=========================================================="
